const CREATE = 'CREATE'

const UPDATE = 'UPDATE'

const DELETE = 'DELETE'

const FETCH_ALL = 'FETCH_ALL'

const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'

const AUTH = 'AUTH'

const LOGOUT = 'LOGOUT'

export { CREATE, UPDATE, DELETE, FETCH_ALL, AUTH, LOGOUT, FETCH_BY_SEARCH }